branches:
  only:
    - master

language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - composer install -n
  - mysql -e 'CREATE DATABASE corvus;'
  - php app/console -n doctrine:migrations:migrate

script: phpunit -c app
