Corvus\AdminBundle\Entity\About:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    firstname:
      type: string
    lastname:
      type: string
    age:
      type: integer
    bio:
      type: string
    address:
      type: string
      nullable: true
    location:
      type: string
      nullable: true
    interests_hobbies:
      type: string
      nullable: true
    email_address:
      type: string
    twitter:
      type: string
      nullable: true
    facebook:
      type: string
      nullable: true
  lifecycleCallbacks: {  }
