Corvus\AdminBundle\Entity\Education:
  type: entity
  table: null
  repositoryClass: Corvus\AdminBundle\Entity\EducationRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    row_order:
      type: integer
    education_institute:
      type: string
    qualification:
      type: string
    start_date:
      type: date
    duration:
      type: decimal
    result:
      type: string
  lifecycleCallbacks: {  }
