Corvus\AdminBundle\Entity\GeneralSettings:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    portfolio_title:
      type: string
      length: 255
    portfolio_subtitle:
      type: string
      length: 255
    display_subtitle:
      type: boolean
    path:
      type: string
      nullable: true
    display_logo:
      type: boolean
    global_general_meta_title:
      type: string
    about_meta_title:
      type: string
    education_meta_title:
      type: string
    work_history_meta_title:
      type: string
    project_history_meta_title:
      type: string
    global_work_history_meta_title:
      type: string
    global_project_history_meta_title:
      type: string
  lifecycleCallbacks:
    prePersist: [preUpload]
    preUpdate: [preUpload]
    postPersist: [upload]
    postUpdate: [upload]
    postRemove: [removeUpload]