Corvus\AdminBundle\Entity\GeneralSettings:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    portfolio_title:
      type: string
    portfolio_subtitle:
      type: string
    display_subtitle:
      type: boolean
    path:
      type: string
      nullable: true
    display_logo:
      type: boolean
    global_general_meta_title:
      type: string
    home_meta_title:
      type: string
    about_meta_title:
      type: string
    education_meta_title:
      type: string
    skills_meta_title:
      type: string
    work_history_meta_title:
      type: string
    project_history_meta_title:
      type: string
    global_work_history_meta_title:
      type: string
    global_project_history_meta_title:
      type: string
    analytics:
      type: string
      nullable: true
    footer_text:
      type: string
      length: 1500
      nullable: true