Corvus\AdminBundle\Entity\Image:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    image_title:
      type: string
    path:
      type: string
    description:
      type: string
    updated:
      type: datetime
  manyToOne:
    ProjectHistory:
      targetEntity: Corvus\AdminBundle\Entity\ProjectHistory
      inversedBy: images
      joinColumn:
        name: project_history_id
        referencedColumnName: id
  lifecycleCallbacks: {  }
