Corvus\AdminBundle\Entity\Navigation:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    navigation_order:
      type: integer
    href:
      type: string
    title:
      type: string
    alt:
      type: string
  lifecycleCallbacks: {  }
