Corvus\AdminBundle\Entity\Skills:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    skill_name:
      type: string
      length: 255
    competency:
      type: string
      length: 255
    years_experience:
      type: decimal
    description:
      type: string
      length: 255
  lifecycleCallbacks: {  }
