Corvus\AdminBundle\Entity\Skills:
  type: entity
  table: null
  repositoryClass: Corvus\AdminBundle\Entity\SkillsRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    row_order:
      type: integer
    skill_name:
      type: string
    competency:
      type: string
    years_experience:
      type: decimal
    description:
      type: string
      length: 2500
    can_display_skill:
      type: boolean
    is_quick_skill:
      type: boolean
  lifecycleCallbacks: {  }
