Corvus\AdminBundle\Entity\Skills:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    skill_name:
      type: string
    competency:
      type: string
    years_experience:
      type: decimal
    description:
      type: string
  lifecycleCallbacks: {  }
