Corvus\AdminBundle\Entity\User:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    username:
      type: string
    password:
      type: string
  lifecycleCallbacks: {  }
