Corvus\AdminBundle\Entity\WorkHistory:
  type: entity
  table: null
  repositoryClass: Corvus\AdminBundle\Entity\WorkHistoryRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    slug:
      type: string
      nullable: true
    row_order:
      type: integer
    employer_name:
      type: string
    employer_address:
      type: string
      nullable: true
    employer_phone_number:
      type: string
      nullable: true
    start_date:
      type: date
    end_date:
      type: date
      nullable: true
    is_current_position:
      type: boolean
      default: 0
    role:
      type: string
    duties:
      type: string
      length: 2500
      nullable: true
    feedback_received:
      type: string
      length: 2000
      nullable: true
    reflection:
      type: string
      length: 2000
      nullable: true
    meta_title:
      type: string
    meta_description:
      type: string
      nullable: true
    isPublished:
      type: boolean
      default: 0
  lifecycleCallbacks: {  }
