parameters:
    FrontendBundleResourcePath: 'src/Corvus/FrontendBundle/Resources'

imports:
    - { resource: assetic.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: ../../src/Corvus/AdminBundle/Resources/config/config.yml }
    - { resource: ../../src/Corvus/CoreBundle/Resources/config/config.yml }
    - { resource: @ILPBootstrapThemeBundle/Resources/config/config.yml }

ilp_bootstrap_theme:
    theme_base: 'src/Corvus/FrontendBundle/Resources/public/css'
    template_base: 'src/Corvus/FrontendBundle/Resources/views'

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    #trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %corvus.database_driver%
        host:     %corvus.database_host%
        port:     %corvus.database_port%
        dbname:   %corvus.database_name%
        user:     %corvus.database_user%
        password: %corvus.database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    delivery_address:  ~
    spool:     { type: memory }

services: ~
