CorvusFrontendBundle:
    resource: "@CorvusFrontendBundle/Resources/config/routing.yml"
    prefix:   /

CorvusAdminBundle:
    resource: "@CorvusAdminBundle/Resources/config/routing.yml"
    prefix:   /Admin

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
