ilp_bootstrap_theme:
    resource: "@ILPBootstrapThemeBundle/Resources/config/routing.yml"
    prefix:   /

corvus_core:
    resource: "@CorvusCoreBundle/Resources/config/routing.yml"
    prefix:   /

CorvusFrontendBundle:
    resource: "@CorvusFrontendBundle/Resources/config/routing.yml"
    prefix:   /

CorvusAdminBundle:
    resource: "@CorvusAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
