ilp_bootstrap_theme:
    resource: "@ILPBootstrapThemeBundle/Resources/config/routing.yml"
    prefix:   /

corvus_core:
    resource: "@CorvusCoreBundle/Resources/config/routing.yml"
    prefix:   /

# Import Frontend Routes
frontend:
    resource: "@CorvusFrontendBundle/Controller"
    type:     annotation
    prefix:   /

frontend_login:
    pattern:  /login
    methods:  [GET|POST]
    defaults: { _controller: CorvusFrontendBundle:Security:login }

# Frontend Security
frontend_login_check:
    pattern:  /login_check
    methods:  [POST]

frontend_logout:
    pattern:  /logout
    methods:  [GET]

admin:
    resource: "@CorvusAdminBundle/Controller"
    type:     annotation
    prefix:   /admin

admin_yml:
    resource: "@CorvusAdminBundle/Resources/Config/routing.yml"
    prefix:   /admin

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
