#jms_security_extra:
#    secure_all_services: false
#    expressions: true

security:
    encoders:
        Corvus\AdminBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    providers:
        user_db:
            entity: { class: Corvus\AdminBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /admin
                csrf_provider: form.csrf_provider
                csrf_parameter: _corvus_csfr_token
            logout: ~

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
