twig:
    globals:
        corvus_version: 0.1.1

assetic:
    bundles:        [CorvusFrontendBundle, CorvusAdminBundle]

services:
    portfolioinforepository:
        class: Corvus\FrontendBundle\Extension\PortfolioInfoRepository
        calls:
            - [setEntityManager, ['@doctrine']]
            - [setRequestStack, ['@request_stack']]
            - [setRouter, ['@router']]
#        strict: false
    corvus.twig.extension.portfolio_info:
        class: Corvus\FrontendBundle\Extension\PortfolioInfoRepositoryExtension
        calls:
            - [setPortfolioInfoRepository, ['@portfolioinforepository']]
        tags:
            - { name: twig.extension }
    fileuploader:
        class: Corvus\AdminBundle\Extension\FileUploader
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }