twig:
    globals:
        corvus_version: 1.02

assetic:
    bundles:        [CorvusFrontendBundle, CorvusAdminBundle]

services:
    portfolioinforepository:
        class: Corvus\FrontendBundle\Extension\PortfolioInfoRepository
        arguments: [@doctrine.orm.default_entity_manager]
    corvus.twig.extension.portfolio_info:
        class: Corvus\FrontendBundle\Extension\PortfolioInfoRepositoryExtension
        arguments: [@portfolioinforepository]
        tags:
            - { name: twig.extension }
    validator.corvus.change_password:
        class: Corvus\AdminBundle\Validator\Constraints\ChangePasswordValidator
        arguments: [@service_container]
        tags:
            - { name: validator.constraint_validator, alias: cpassword_validator }
    kernel.listener.covus_admin_exception_listener:
        class: Corvus\AdminBundle\EventListener\CorvusAdminExceptionListener
        arguments: [@twig]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    fileuploader:
        class: Corvus\AdminBundle\Extension\FileUploader
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }