CorvusAdminBundle_Home:
    pattern:  /
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:index }

CorvusAdminBundle_GeneralSettings:
    pattern: /general-settings
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:GeneralSettings:generalSettings }

CorvusAdminBundle_Analytics:
    pattern: /analytics
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:GeneralSettings:analytics }

CorvusAdminBundle_Security:
    pattern: /security
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:GeneralSettings:security }

CorvusAdminBundle_SiteDesign:
    pattern: /site-design
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Default:siteDesign }

CorvusAdminBundle_ThemeEditor:
    pattern: /theme-editor
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Default:themeEditor }

CorvusAdminBundle_Education:
    pattern: /education
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:education }

CorvusAdminBundle_NewEducation:
    pattern: /education/new
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Education:new }

CorvusAdminBundle_UpEducationOrder:
    pattern: /education/order/up/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Education:orderUp }
    requirements:
        id: \d+

CorvusAdminBundle_DownEducationOrder:
    pattern: /education/order/down/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Education:orderDown }
    requirements:
        id: \d+

CorvusAdminBundle_EditEducation:
    pattern: /education/edit/id/{id}
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Education:edit }

CorvusAdminBundle_DeleteEducationId:
    pattern: /education/delete/id/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Education:delete }
    requirements:
        id: \d+

CorvusAdminBundle_DeleteEducation:
    pattern: /education/delete
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Education:delete, id: null }

CorvusAdminBundle_ProjectHistory:
    pattern: /project-history
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:projectHistory }

CorvusAdminBundle_NewProjectHistory:
    pattern: /project-history/new
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:new }

CorvusAdminBundle_UpProjectHistoryOrder:
    pattern: /project-history/order/up/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:orderUp }
    requirements:
        id: \d+

CorvusAdminBundle_DownProjectHistoryOrder:
    pattern: /project-history/order/down/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:orderDown }
    requirements:
        id: \d+

CorvusAdminBundle_EditProjectHistory:
    pattern: /project-history/edit/id/{id}
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:edit }

CorvusAdminBundle_DeleteProjectHistoryId:
    pattern: /project-history/delete/id/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:delete }
    requirements:
        id: \d+

CorvusAdminBundle_DeleteProjectHistory:
    pattern: /project-history/delete
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:delete, id: null }

CorvusAdminBundle_WorkHistory:
    pattern: /work-history
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:workHistory }

CorvusAdminBundle_NewWorkHistory:
    pattern: /work-history/new
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:new }

CorvusAdminBundle_UpWorkHistoryOrder:
    pattern: /work-history/order/up/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:orderUp }
    requirements:
        id: \d+

CorvusAdminBundle_DownWorkHistoryOrder:
    pattern: /work-history/order/down/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:orderDown }
    requirements:
        id: \d+

CorvusAdminBundle_EditWorkHistory:
    pattern: /work-history/edit/id/{id}
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:edit }

CorvusAdminBundle_DeleteWorkHistoryId:
    pattern: /work-history/delete/id/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:delete }
    requirements:
        id: \d+

CorvusAdminBundle_DeleteWorkHistory:
    pattern: /work-history/delete
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:delete, id: null }

CorvusAdminBundle_Downloads:
    pattern: /downloads
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:downloads }

CorvusAdminBundle_About:
    pattern: /about
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Default:about }

CorvusAdminBundle_Skills:
    pattern: /skills
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:skills }

CorvusAdminBundle_NewSkills:
    pattern: /skills/new
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Skills:new }

CorvusAdminBundle_UpSkillsOrder:
    pattern: /skills/order/up/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Skills:orderUp }
    requirements:
        id: \d+

CorvusAdminBundle_DownSkillsOrder:
    pattern: /skills/order/down/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Skills:orderDown }
    requirements:
        id: \d+

CorvusAdminBundle_EditSkills:
    pattern: /skills/edit/id/{id}
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Skills:edit }
    requirements:
        id: \d+

CorvusAdminBundle_DeleteSkillsId:
    pattern: /skills/delete/id/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Skills:delete }
    requirements:
        id: \d+

CorvusAdminBundle_DeleteSkills:
    pattern: /skills/delete
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Skills:delete, id: null }

CorvusAdminBundle_Navigation:
    pattern: /navigation
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:navigation }

CorvusAdminBundle_NewNavigation:
    pattern: /navigation/new
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Navigation:new }

CorvusAdminBundle_UpNavigationOrder:
    pattern: /navigation/order/up/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Navigation:orderUp }
    requirements:
        id: \d+

CorvusAdminBundle_DownNavigationOrder:
    pattern: /navigation/order/down/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Navigation:orderDown }
    requirements:
        id: \d+

CorvusAdminBundle_EditNavigation:
    pattern: /navigation/edit/id/{id}
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Navigation:edit }
    requirements:
        id: \d+

CorvusAdminBundle_DeleteNavigationId:
    pattern: /navigation/delete/id/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Navigation:delete }
    requirements:
        id: \d+

CorvusAdminBundle_DeleteNavigation:
    pattern: /navigation/delete
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Navigation:delete, id: null }