# Education Routes

admin_education_new:
    pattern: /education/new
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Education:new }

admin_education_order_up:
    pattern: /education/order/up/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Education:orderUp }
    requirements:
        id: \d+

admin_education_order_down:
    pattern: /education/order/down/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Education:orderDown }
    requirements:
        id: \d+

admin_education_edit:
    pattern: /education/edit/id/{id}
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Education:edit }

admin_education_delete_id:
    pattern: /education/delete/id/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Education:delete }
    requirements:
        id: \d+

admin_education_delete:
    pattern: /education/delete
    methods: [DELETE]
    defaults: { _controller: CorvusAdminBundle:Education:delete, id: null }

# Project History Routes

admin_project_history_new:
    pattern: /project-history/new
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:new }

admin_project_history_order_up:
    pattern: /project-history/order/up/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:orderUp }
    requirements:
        id: \d+

admin_project_history_order_down:
    pattern: /project-history/order/down/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:orderDown }
    requirements:
        id: \d+

admin_project_history_publish:
    pattern: /project-history/publish/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:publish }
    requirements:
        id: \d+

admin_project_history_depublish:
    pattern: /project-history/depublish/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:depublish }
    requirements:
        id: \d+

admin_project_history_edit:
    pattern: /project-history/edit/id/{id}
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:edit }

admin_project_history_delete_id:
    pattern: /project-history/delete/id/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:delete }
    requirements:
        id: \d+

admin_project_history_delete:
    pattern: /project-history/delete
    methods: [DELETE]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:delete, id: null }

# Work History Routes

admin_work_history:
    pattern: /work-history
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:workHistory }

admin_work_history_new:
    pattern: /work-history/new
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:new }

admin_work_history_order_up:
    pattern: /work-history/order/up/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:orderUp }
    requirements:
        id: \d+

admin_work_history_order_down:
    pattern: /work-history/order/down/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:orderDown }
    requirements:
        id: \d+

admin_work_history_publish:
    pattern: /work-history/publish/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:publish }
    requirements:
        id: \d+

admin_work_history_depublish:
    pattern: /work-history/depublish/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:depublish }
    requirements:
        id: \d+

admin_work_history_edit:
    pattern: /work-history/edit/id/{id}
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:edit }

admin_work_history_delete_id:
    pattern: /work-history/delete/id/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:delete }
    requirements:
        id: \d+

admin_work_history_delete:
    pattern: /work-history/delete
    methods: [DELETE]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:delete, id: null }

# Skills Routes

admin_skills_new:
    pattern: /skills/new
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Skills:new }

admin_skills_order_up:
    pattern: /skills/order/up/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Skills:orderUp }
    requirements:
        id: \d+

admin_skills_order_down:
    pattern: /skills/order/down/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Skills:orderDown }
    requirements:
        id: \d+

admin_skills_edit:
    pattern: /skills/edit/id/{id}
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Skills:edit }
    requirements:
        id: \d+

admin_skills_delete_id:
    pattern: /skills/delete/id/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Skills:delete }
    requirements:
        id: \d+

admin_skills_delete:
    pattern: /skills/delete
    methods: [DELETE]
    defaults: { _controller: CorvusAdminBundle:Skills:delete, id: null }

# Navigation Routes

admin_navigation_new:
    pattern: /navigation/new
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Navigation:new }

admin_navigation_order_up:
    pattern: /navigation/order/up/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Navigation:orderUp }
    requirements:
        id: \d+

admin_navigation_order_down:
    pattern: /navigation/order/down/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Navigation:orderDown }
    requirements:
        id: \d+

admin_navigation_edit:
    pattern: /navigation/edit/id/{id}
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Navigation:edit }
    requirements:
        id: \d+

admin_navigation_delete_id:
    pattern: /navigation/delete/id/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Navigation:delete }
    requirements:
        id: \d+

admin_navigation_delete:
    pattern: /navigation/delete
    methods: [DELETE]
    defaults: { _controller: CorvusAdminBundle:Navigation:delete, id: null }