CorvusAdminBundle_Home:
    pattern:  /
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:index }

CorvusAdminBundle_GeneralSettings:
    pattern: /GeneralSettings
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:GeneralSettings:generalSettings }

CorvusAdminBundle_Analytics:
    pattern: /Analytics
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:GeneralSettings:analytics }

CorvusAdminBundle_Security:
    pattern: /Security
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:GeneralSettings:security }

CorvusAdminBundle_SiteDesign:
    pattern: /SiteDesign
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:siteDesign }

CorvusAdminBundle_Education:
    pattern: /Education
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:education }

CorvusAdminBundle_NewEducation:
    pattern: /Education/New
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Education:new }

CorvusAdminBundle_UpEducationOrder:
    pattern: /Education/Order/Up/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Education:orderUp }
    requirements:
        id: \d+

CorvusAdminBundle_DownEducationOrder:
    pattern: /Education/Order/Down/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Education:orderDown }
    requirements:
        id: \d+

CorvusAdminBundle_EditEducation:
    pattern: /Education/Edit/id/{id}
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Education:edit }

CorvusAdminBundle_DeleteEducationId:
    pattern: /Education/Delete/id/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Education:delete }
    requirements:
        id: \d+

CorvusAdminBundle_DeleteEducation:
    pattern: /Education/Delete
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Education:delete, id: null }

CorvusAdminBundle_ProjectHistory:
    pattern: /ProjectHistory
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:projectHistory }

CorvusAdminBundle_NewProjectHistory:
    pattern: /ProjectHistory/New
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:new }

CorvusAdminBundle_UpProjectHistoryOrder:
    pattern: /ProjectHistory/Order/Up/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:orderUp }
    requirements:
        id: \d+

CorvusAdminBundle_DownProjectHistoryOrder:
    pattern: /ProjectHistory/Order/Down/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:orderDown }
    requirements:
        id: \d+

CorvusAdminBundle_EditProjectHistory:
    pattern: /ProjectHistory/Edit/id/{id}
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:edit }

CorvusAdminBundle_DeleteProjectHistoryId:
    pattern: /ProjectHistory/Delete/id/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:delete }
    requirements:
        id: \d+

CorvusAdminBundle_DeleteProjectHistory:
    pattern: /ProjectHistory/Delete
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:ProjectHistory:delete, id: null }

CorvusAdminBundle_WorkHistory:
    pattern: /WorkHistory
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:workHistory }

CorvusAdminBundle_NewWorkHistory:
    pattern: /WorkHistory/New
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:new }

CorvusAdminBundle_UpWorkHistoryOrder:
    pattern: /WorkHistory/Order/Up/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:orderUp }
    requirements:
        id: \d+

CorvusAdminBundle_DownWorkHistoryOrder:
    pattern: /WorkHistory/Order/Down/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:orderDown }
    requirements:
        id: \d+

CorvusAdminBundle_EditWorkHistory:
    pattern: /WorkHistory/Edit/id/{id}
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:edit }

CorvusAdminBundle_DeleteWorkHistoryId:
    pattern: /WorkHistory/Delete/id/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:delete }
    requirements:
        id: \d+

CorvusAdminBundle_DeleteWorkHistory:
    pattern: /WorkHistory/Delete
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:WorkHistory:delete, id: null }

CorvusAdminBundle_Downloads:
    pattern: /Downloads
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:downloads }

CorvusAdminBundle_About:
    pattern: /About
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Default:about }

CorvusAdminBundle_Skills:
    pattern: /Skills
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:skills }

CorvusAdminBundle_NewSkills:
    pattern: /Skills/New
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Skills:new }

CorvusAdminBundle_UpSkillsOrder:
    pattern: /Skills/Order/Up/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Skills:orderUp }
    requirements:
        id: \d+

CorvusAdminBundle_DownSkillsOrder:
    pattern: /Skills/Order/Down/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Skills:orderDown }
    requirements:
        id: \d+

CorvusAdminBundle_EditSkills:
    pattern: /Skills/Edit/id/{id}
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Skills:edit }
    requirements:
        id: \d+

CorvusAdminBundle_DeleteSkillsId:
    pattern: /Skills/Delete/id/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Skills:delete }
    requirements:
        id: \d+

CorvusAdminBundle_DeleteSkills:
    pattern: /Skills/Delete
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Skills:delete, id: null }

CorvusAdminBundle_Navigation:
    pattern: /Navigation
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Default:navigation }

CorvusAdminBundle_NewNavigation:
    pattern: /Navigation/New
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Navigation:new }

CorvusAdminBundle_UpNavigationOrder:
    pattern: /Navigation/Order/Up/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Navigation:orderUp }
    requirements:
        id: \d+

CorvusAdminBundle_DownNavigationOrder:
    pattern: /Navigation/Order/Down/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Navigation:orderDown }
    requirements:
        id: \d+

CorvusAdminBundle_EditNavigation:
    pattern: /Navigation/Edit/id/{id}
    methods: [GET|POST]
    defaults: { _controller: CorvusAdminBundle:Navigation:edit }
    requirements:
        id: \d+

CorvusAdminBundle_DeleteNavigationId:
    pattern: /Navigation/Delete/id/{id}
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Navigation:delete }
    requirements:
        id: \d+

CorvusAdminBundle_DeleteNavigation:
    pattern: /Navigation/Delete
    methods: [GET]
    defaults: { _controller: CorvusAdminBundle:Navigation:delete, id: null }