services:
    navigation.form.type:
        class: Corvus\AdminBundle\Form\Type\NavigationType
        calls:
            - [setPortfolioInfoRepository, ['@portfolioinforepository']]
        tags:
            - { name: form.type, alias: navigation }