# src/Corvus/AdminBundle/Resources/config/validation.yml
Corvus\AdminBundle\Entity\About:
    properties:
        firstname:
            - NotNull: ~
        lastname:
            - NotNull: ~
        age:
            - NotNull: ~
            - Length:
                min: 0
                max: 130
        bio:
            - NotNull: ~
        email_address:
            - NotNull: ~
            - Email: ~

Corvus\AdminBundle\Entity\Education:
    properties:
        row_order:
            - NotNull: ~
        education_institute:
            - NotNull: ~
        qualification:
            - NotNull: ~
        start_date:
            - NotNull: ~
            - Date: ~

Corvus\AdminBundle\Entity\GeneralSettings:
    properties:
        portfolio_title:
            - NotNull: ~

Corvus\AdminBundle\Entity\File:
    properties:
        file_title:
            - NotNull: ~
        description:
            - NotNull: ~
        path:
            - NotNull: ~

Corvus\AdminBundle\Entity\Navigation:
    properties:
        row_order:
            - NotNull: ~
        href:
            - NotNull: ~
        title:
            - NotNull: ~
        alt:
            - NotNull: ~

Corvus\AdminBundle\Entity\ProjectHistory:
    properties:
        row_order:
            - NotNull: ~
        project_name:
            - NotNull: ~
        project_description:
            - NotNull: ~
        role:
            - NotNull: ~
        meta_title:
            - NotNull: ~

Corvus\AdminBundle\Entity\Skills:
    properties:
        row_order:
            - NotNull: ~
        skill_name:
            - NotNull: ~

Corvus\AdminBundle\Entity\WorkHistory:
    properties:
        row_order:
            - NotNull: ~
        employer_name:
            - NotNull: ~
        start_date:
            - NotNull: ~
        role:
            - NotNull: ~
        meta_title:
            - NotNull: ~