CorvusFrontendBundle_homepage:
    pattern:  /
    methods: [GET]
    defaults: { _controller: CorvusFrontendBundle:Default:index }

CorvusFrontendBundle_Education:
    pattern: /education
    methods: [GET]
    defaults: { _controller: CorvusFrontendBundle:Default:education }

CorvusFrontendBundle_Skills:
    pattern: /skills
    methods: [GET]
    defaults: { _controller: CorvusFrontendBundle:Default:skills }

CorvusFrontendBundle_About:
    pattern: /about
    methods: [GET]
    defaults: { _controller: CorvusFrontendBundle:Default:about }

CorvusFrontendBundle_WorkHistory:
    pattern: /work-history
    methods: [GET]
    defaults: { _controller: CorvusFrontendBundle:Default:workHistory }

CorvusFrontendBundle_ProjectHistory:
    pattern: /project-history
    methods: [GET]
    defaults: { _controller: CorvusFrontendBundle:Default:projectHistory }

CorvusFrontendBundle_Login:
    pattern: /login
    methods: [GET|POST]
    defaults: { _controller: CorvusFrontendBundle:Security:login }

CorvusFrontendBundle_LoginCheck:
    pattern: /login_check
    methods: [POST]

CorvusFrontendBundle_Logout:
    pattern: /logout
    methods: [GET]